package com.launchpad.demo.shopping;

import com.launchpad.demo.models.dynamodb.Item;
import com.launchpad.demo.models.dynamodb.ItemType;
import com.launchpad.demo.models.RequestBodyItem;

import java.util.UUID;

public class ItemDecorator {

    public static Item decorate(RequestBodyItem requestBodyItem) {
        ItemType itemType = FoodToItemTypeMapper.stringToItemType(requestBodyItem.getName()); // no null check needed - handled in stringToItemType
        return Item.builder()
                .id(UUID.randomUUID().toString()) // cheap hack bc @DynamoDBAutoGeneratedKey isn't working rip :(
                .name(requestBodyItem.getName())
                .price(requestBodyItem.getPrice())
                .size(requestBodyItem.getSize())
                .quantity(requestBodyItem.getQuantity())
                .itemType(itemType)
                .isBought(false)
                .isPromoted(false)
                .build();
    }
}
